# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/varnish"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/redis"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/rabbitmq"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm/xdebug3"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm/node"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm/magento2"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm/magento2/xdebug3"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm/magento2/blackfire"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm/magento1"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm/magento1/xdebug3"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm/magento1/blackfire"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/php-fpm/blackfire"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/opensearch"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/magepack"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/nginx"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mysql"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mariadb"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/mailhog"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/elasticsearch"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/dnsmasq"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/dashboard"
    schedule:
      interval: "daily"
