name: Docker Image Dragonfly DB
on:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - .trigger
      - dragonfly/**
      - .github/workflows/*dragonfly*


jobs:
  dragonfly:
    name: Dragonfly DB
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "0.6"
          - "0.7"
          - "0.8"
          - "0.9"
          - "0.10"
          - "0.11"
          - "0.12"
          - "0.13"
          - "0.14"
          - "0.15"
          - "0.16"
          - "0.17"
          - "1.0"
          - "1.1"
          - "1.2"
          - "1.3"

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - name: Set build-args
        run: |-
          ESCAPED_VERSION="$(echo ${{ matrix.version }} | sed 's/\./\\\./g')"
          DRAGONFLY_VERSION=$(
            docker run --rm gcr.io/go-containerregistry/crane:v0.8.0 ls docker.dragonflydb.io/dragonflydb/dragonfly \
            | egrep "^v${ESCAPED_VERSION}\.[0-9]+(\.[0-9]+)?\$" | sort -Vr | head -n1
          )
          echo "DRAGONFLY_VERSION=${DRAGONFLY_VERSION}" | tee /dev/stderr >> $GITHUB_ENV

      - uses: docker/build-push-action@v4
        with:
          context: dragonfly
          platforms: linux/amd64,linux/arm64
          build-args: DRAGONFLY_VERSION=${{ env.DRAGONFLY_VERSION }}
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/dragonfly:${{ matrix.version }}, rollupdev/dragonfly:${{ matrix.version }}
        if: ${{ !env.ACT && github.ref == 'refs/heads/master'}}
