name: Docker Image RollDev Dashboard
on:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - .trigger
      - startpage/**
      - .github/workflows/*startpage*

jobs:
  startpage:
    name: Startpage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v4
        with:
          context: startpage
          platforms: linux/amd64,linux/arm64
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/rolldev-startpage:latest
        if: ${{ !env.ACT && github.ref == 'refs/heads/master'}}