name: Docker Image RabbitMQ
on:
  schedule:
    - cron: "0 6 * * *" # 6 AM Daily
  push:
    paths:
      - .trigger
      - rabbitmq/**
      - .github/workflows/*rabbitmq*

jobs:
  rabbitmq:
    name: RabbitMQ
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
#        include:
#          - version: "3.12"
#            modifier: "-rc"

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ !env.ACT }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ !env.ACT }}

      - uses: docker/build-push-action@v5
        with:
          context: rabbitmq
          platforms: linux/amd64,linux/arm64
          build-args: RABBITMQ_VERSION=${{ matrix.version }}${{ matrix.modifier }}
          push: ${{ github.ref == 'refs/heads/master' && !env.ACT }}
          tags: ghcr.io/${{ github.repository_owner }}/rabbitmq:${{ matrix.version }}${{ matrix.modifier }}, rollupdev/rabbitmq:${{ matrix.version }}${{ matrix.modifier }}
        if: ${{ !env.ACT && github.ref == 'refs/heads/master'}}